POSTGRES_PASSWORD: ENC[AES256_GCM,data:VQz+x8tp2T1gp50AMhmydGWS9zbHUD0aZt+7Ow==,iv:+QQMxHj0E3cIHMjFhHOHmR627HRe8Zat2AkgO12R9PI=,tag:1q8N1nfWS1vss596cEtBdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age154d73sxvppr3fwgwey6he76ctxm7jn2y4e0f2ckaumx6edlnzvssz8kw0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwemZWd2dOYTdSQ3pra3kz
            b01oU1cxbEdOVDlaSmY1Njk4VjFUeG11Z2dFCmRTYS85bmRsMVJpMlF3LzU0WExI
            TVcxODNyMFhpdmhBMWo4VWZaUnczR3cKLS0tIHlBZnRZbkRNWkdSTmFhNW9UK0Mw
            cno4QllKVU5TUnNGQjJZYTdWYnhZRlEKEO/ueXeoXNJAkaqEkOfrC2x4msviT8OI
            pd2x5fldJVbp6TTU1K2RLfh/o43RTAyhIyODqVaNMgFKwwlnK2j6+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T14:56:53Z"
    mac: ENC[AES256_GCM,data:AR0MG4OH4S5awiCkcOojVyGj3yPI7Lcc5EHPsOHWNnTZmaIktURmrhQcIu7OP9Z8kFPlCiZTWeRHQOX5M5ajdc2yfAizTKRFpam9fMLQQj3s6tk881FPUaq9CmIyt8fkVi9NcdJIR5dAyklVUTIvEVhO200JQRQt/wFeJVtMEvc=,iv:nZnZPsdbpKH9N8H2NPfxvybRkbJGREaDqngO1lpsiVw=,tag:ngVHLzLxodnOtEhuXiVAQQ==,type:str]
    pgp:
        - created_at: "2024-06-15T14:56:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DyChR8TlJU3cSAQdAdlizKxGIS0ytnOxZQelkqJNs193Nw0WKx1Za3DZO8AUw
            vjiGRG9CeNXiSDZr7tLeg8zvVwu4+aH11eAFhEYprTg4kNj+dntld07LJNUOb1UM
            1GgBCQIQ4j4EYTp5AwcEojVuQi3f3MW0yOcnead+33GP1lStAL/FXjfLs9jzlCud
            om1A1NQyWWkeM2xaW39o0zDkuinUL5vbw5/Kmnz2XEoMVIVqceQJ6tbGc63u2hLi
            J4Mpvrs2ZCVj9A==
            =31bl
            -----END PGP MESSAGE-----
          fp: B12C44A2E9386B993A8FFC53F822CE4444B1D606
    unencrypted_suffix: _unencrypted
    version: 3.8.1
