- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  tags: packages

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
  tags: packages

- name: Configure timezone
  community.general.timezone:
    name: "{{ timezone }}"
  notify: restart rsyslog
  tags: timezone

- name: Create admin user
  ansible.builtin.user:
    name: "{{ admin_user_name }}"
    shell: "{{ admin_user_shell }}"
    groups: "{{ admin_user_groups }}"
    append: true
  tags: users

- name: Configure SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^Port", line: "Port {{ ssh_port }}" }
    - {
        regexp: "^PasswordAuthentication",
        line: 'PasswordAuthentication {{ ssh_password_authentication | ternary("yes", "no") }}',
      }
  notify: restart ssh
  tags: ssh

- name: Set up admin user SSH key from GitHub
  ansible.posix.authorized_key:
    user: "{{ admin_user_name }}"
    key: "https://github.com/{{ github_username }}.keys"
    state: present
  when:
    - admin_user_name is defined
    - github_username is defined
  tags: ssh
