#!/bin/sh
#
# Ensures all tmux plugins are installed and up to date.

tmux="$HOME/.config/tmux"
tpm="$tmux/plugins/tpm"

if [ -d "$tpm" ]; then
        cd "$tpm"
        git pull
else
        mkdir -p "$tpm"
        git clone https://github.com/tmux-plugins/tpm "$tpm"
fi

TMUX= tmux -f "$tmux/plugins.conf" new-session -s temp bash -c "
        $tpm/bin/install_plugins
        $tpm/bin/update_plugins
        sleep 0.5
"
