---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-script
data:
  setup_db.sql: |
    CREATE DATABASE IF NOT EXISTS ${MYSQL_07_08_DATABASE} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-create-db-job
spec:
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: mariadb-create-db
          image: mariadb:11
          command:
            [
              "sh",
              "-c",
              "mariadb -h mariadb-service -u root -p${MYSQL_ROOT_PASSWORD} < /mnt/setup_db.sql",
            ]
          volumeMounts:
            - name: script-volume
              mountPath: /mnt
      volumes:
        - name: script-volume
          configMap:
            name: mariadb-init-script
      restartPolicy: Never
  backoffLimit: 1
