---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-script
data:
  setup_db.sql: |
    ALTER USER 'admin'@'localhost' IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
    RENAME USER 'admin'@'localhost' TO 'admin'@'%';
    GRANT ALL PRIVILEGES ON *.* TO 'SELECT * FROM mysql.user WHERE User='admin';
dmin'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-create-db-job
spec:
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: mariadb-create-db
          image: mariadb:11
          command:
            [
              "sh",
              "-c",
              "mariadb -h mariadb-service -u root -p${MYSQL_ROOT_PASSWORD} < /mnt/setup_db.sql",
            ]
          volumeMounts:
            - name: script-volume
              mountPath: /mnt
      volumes:
        - name: script-volume
          configMap:
            name: mariadb-init-script
      restartPolicy: Never
  backoffLimit: 1
