MEILI_MASTER_KEY: ENC[AES256_GCM,data:JpoXuEHM08FSOs7zCw4kdOVv3WHs6fyQH1kqPkwQ/fxzBJarMXupzCxf,iv:LjiVMcUD5uaTxOH6oxRvNllM2IuWujcZIdCf6qoTab0=,tag:skpyKnmRHy9Bg4sEZc1qMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age154d73sxvppr3fwgwey6he76ctxm7jn2y4e0f2ckaumx6edlnzvssz8kw0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYlF1TUhINVQ3TFY5d0hU
            d1ZsNy9BWjJlVm5neG16T1hmN2FoQXlraW5RCkNoV2NCR2g0V1FXZklUSllET3JE
            cmE4dVFIN0Vsb3RpbERpcnVmaTFvdG8KLS0tIHU3ZTQrbGhtM0Z0eFBpbnhWMTZx
            WjhDUHdxVVFNajR2NU1sSy9aN0wzRTAKZ7sqT5lR02jYgYBlXbnkKEBBTqSS+aAJ
            DqO+3TlqRSOMMzSvyTtS3aaRyJ1s8L0TIKHgsh1N7I5RVBenDS80hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T17:55:13Z"
    mac: ENC[AES256_GCM,data:34ScC8Dipxpkx0egyFHcLhK95a0GUz8kXsbx8JraV38sghgKDP3cddlkv5xG1DYg9ueLSbyCFSfSbJEAQzm3ncib/jWFeujhfT6XIRsCCBADUx3KicqSxH73MIrQBiDFaIkXe0ZD6MBCbjcMSyKH6ruPztfbLbCZf+jiBsAmiAg=,iv:lC9Q32IBEE94XxkVrUK5IP+w8229JzxEUq2q25GnclI=,tag:of1eGthWfXpfr8eq5k2YFw==,type:str]
    pgp:
        - created_at: "2024-06-09T17:58:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DyChR8TlJU3cSAQdADXJUeCcKBwX/GrWoJcohhLol5/GiJGAQ2gcCj1VYvTAw
            B1XDVwNRyHd8Lp0jH+evQhYLkzkb++iGJT9s335bhAE9iuGz83h1sH08Om6bIfD9
            1GgBCQIQzCUkoGh5BNbdJXBxa7qno+jyLRFXve0fezhbFbyXSaFLq/47rjKXL0SW
            ETanakNXA4vDmzpZ5opek5f1ycZFYwzkzhHyDLVRuh1uF9BepE3WZngJF7PN0XcQ
            SPNoJKk+Mgm94g==
            =lrwn
            -----END PGP MESSAGE-----
          fp: B12C44A2E9386B993A8FFC53F822CE4444B1D606
    unencrypted_suffix: _unencrypted
    version: 3.8.1
