---
apiVersion: v1
kind: Secret
metadata:
  name: read-secrets
type: Opaque
stringData:
  ADMIN_EMAIL: "${ADMIN_EMAIL}"
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  ADMIN_API_KEY: "${ADMIN_API_KEY}"
  IMT_API: "${IMT_API}"
  DIRECTUS_API: "${DIRECTUS_API}"
  COOKIE_SECRET: "${COOKIE_SECRET}"
  IMMERSIVE_TRANSLATE_TOKEN: "${IMMERSIVE_TRANSLATE_TOKEN}"
  CLOUDFLARE_ACCESS_KEY_ID: "${CLOUDFLARE_ACCESS_KEY_ID}"
  CLOUDFLARE_ACCESS_KEY_SECRET: "${CLOUDFLARE_ACCESS_KEY_SECRET}"
  CLOUDFLARE_ACCOUNT_ID: "${CLOUDFLARE_ACCOUNT_ID}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  OPENAI_API_ENDPOINT: "${OPENAI_API_ENDPOINT}"
  FEISHU_STATUS_BOT_URL: "${FEISHU_STATUS_BOT_URL}"
  WORKOS_API_KEY: "${WORKOS_API_KEY}"
  WORKOS_CLIENT_ID: "${WORKOS_CLIENT_ID}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-deployment
  labels:
    app: read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read
  template:
    metadata:
      labels:
        app: read
    spec:
      containers:
        - name: read
          image: ${IMAGE}
          ports:
            - containerPort: 8002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PROD
              value: "1"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: DB_HOST
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: DB_PASSWORD
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: ADMIN_API_KEY
            - name: IMT_API
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: IMT_API
            - name: DIRECTUS_API
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: DIRECTUS_API
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: COOKIE_SECRET
            - name: IMMERSIVE_TRANSLATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: IMMERSIVE_TRANSLATE_TOKEN
            - name: CLOUDFLARE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: CLOUDFLARE_ACCESS_KEY_ID
            - name: CLOUDFLARE_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: CLOUDFLARE_ACCESS_KEY_SECRET
            - name: CLOUDFLARE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: CLOUDFLARE_ACCOUNT_ID
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: OPENAI_API_ENDPOINT
            - name: FEISHU_STATUS_BOT_URL
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: FEISHU_STATUS_BOT_URL
            - name: WORKOS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: WORKOS_API_KEY
            - name: WORKOS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: read-secrets
                  key: WORKOS_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: read-service
spec:
  selector:
    app: read
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: read-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: ${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: read-service
                port:
                  number: 80
